services:
  mongo:
    image: mongo:8.0.1
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: illm
    volumes:
      - ./mongo-data:/data/db
    networks:
      - illm

  ollama-llm:
    image: ollama/ollama:latest
    ports:
      - 7869:11434
    volumes:
      - .:/code
      - ./ollama/ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    networks:
      - illm

  go-server:
    image: siddh34/illm-golang:0.0.1
    depends_on:
      - mongo
      - ollama-llm
    environment:
      LLAMA_URL: http://ollama-llm:11434/
    ports:
      - "8081:8090"
    networks:
      - illm

volumes:
  ollama:
  mongo-data:


networks:
  illm:
    driver: bridge